name: Flujo de trabajo para publicar, ejecutar los tests secuencialmente.
on:
  push:  
    branches: [arreglosCole]
  pull_request: 

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construir el .jar
        run: |
          chmod +x gradlew  
          ls -a > echo
          ./gradlew assemble
      - name: Mi uvus
        run: |
          echo "pabkramar"
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'

          java-version: '16'
      - name: Probando el código
        run: |
          chmod +x gradlew        
          ./gradlew test
      - name: Mi uvus
        run: |
          echo "pabkramar"

